{% set name = "clin_data_tools" %}
{% set version = "0.1.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: ..

build:
  # 不要 noarch: python
  script: pip install .
  number: 3
  entry_points:
    - check_col = clin_data_tools.check_col:main

requirements:
  build:
    - python {{ python }}        # <-- 用 Jinja2 变量，而不是 "python >=3.8"
    - pip
    - setuptools
    - wheel
    - pandas >=1.0
    - openpyxl >=3.0
    - numpy >=1.22
  run:
    - python {{ python }}        # <-- 同理
    - pandas >=1.0
    - openpyxl >=3.0
    - numpy >=1.22

test:
  imports:
    - clin_data_tools          # 测试包是否能正确导入
  source_files:
    - tests
  commands:
    - pytest tests/
  requires:
    - pytest
    - pandas
    - openpyxl
    - numpy

about:
  home: https://github.com/archerrish/clin_data_tools
  license: GPL
  license_file: LICENSE
  summary: "A toolkit for clinical data validation and manipulation"
  description: |
    Clin Data Tools provides utilities for validating clinical data files,
    including CSV and Excel.
  dev_url: https://github.com/archerrish/clin_data_tools
