package:
  name: clin_data_tools        # 包名
  version: "0.1.1"             # 当前版本号

source:
  path: ..                      # 指定源码路径

build:
  # noarch: python               # 指定为跨平台 Python 包
  script: pip install .        # 使用 pip 安装，替代 python setup.py install
  number: 2                    # 构建编号

requirements:
  build:
    - python >=3.8
    - pip                     # 使用 pip 代替 setuptools 的依赖处理
    - setuptools
    - wheel                   # 确保打包工具完整
    - pandas >=1.0
    - openpyxl >=3.0
    - numpy >=1.22
  run:
    - python >=3.8
    - pandas >=1.0
    - openpyxl >=3.0
    - numpy >=1.22

test:
  imports:
    - clin_data_tools          # 测试包是否能正确导入
  source_files:
    - tests
  commands:
    - pytest tests/
  requires:
    - pytest
    - pandas
    - openpyxl
    - numpy

about:
  home: https://github.com/archerrish/clin_data_tools
  license: GPL
  license_file: LICENSE
  summary: "A toolkit for clinical data validation and manipulation"
  description: |
    Clin Data Tools provides utilities for validating clinical data files,
    including CSV and Excel.
  dev_url: https://github.com/archerrish/clin_data_tools
