name: Conda Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 设置 Conda 环境
      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.8

      # 安装 conda-build
      - name: Install conda-build
        run: conda install -y conda-build pytest

      # 构建并测试包
      - name: Build and test Conda package
        run: conda build conda/
